-- RoktoNet -- bd_thanas reference data
-- Sourced from:
--   * Districts + rural upazilas: nuhil/bangladesh-geocode (government-sourced
--     from bangladesh.gov.bd / Wikipedia; 64 districts, 494 upazilas)
--   * Dhaka metro thanas: dmp.gov.bd/find-your-local-police/ (official DMP
--     list, ~49 stations)
--   * Gazipur metro thanas: gmp.gov.bd + en.wikipedia.org/wiki/Gazipur_Metropolitan_Police
--     (official GMP list, 8 stations, formed 2018)
-- Metro thanas were added on top of the base upazila set because a city's real
-- administrative/policing unit is the "thana", not "upazila" -- e.g. Dhaka's
-- upazila-only entries (Savar, Dhamrai, Keraniganj, Nawabganj, Dohar) cover only
-- the rural area *around* the city, and the same was true for Gazipur (Tongi is
-- a GMP thana, not a rural upazila -- this was the exact case that surfaced the
-- need for this supplement).
--
-- KNOWN LIMITATION (disclosed, not silently assumed complete): only Dhaka and
-- Gazipur's metro thanas are added. Other metro police areas (Chattogram/CMP,
-- Khulna, Rajshahi, Sylhet, Barisal, Rangpur) still only have their rural
-- upazila-level entries. Same method (official metro police station list)
-- extends this later.

INSERT INTO bd_thanas (name, district) VALUES
  ('Debidwar', 'Comilla'),
  ('Barura', 'Comilla'),
  ('Brahmanpara', 'Comilla'),
  ('Chandina', 'Comilla'),
  ('Chauddagram', 'Comilla'),
  ('Daudkandi', 'Comilla'),
  ('Homna', 'Comilla'),
  ('Laksam', 'Comilla'),
  ('Muradnagar', 'Comilla'),
  ('Nangalkot', 'Comilla'),
  ('Comilla Sadar', 'Comilla'),
  ('Meghna', 'Comilla'),
  ('Monohargonj', 'Comilla'),
  ('Sadarsouth', 'Comilla'),
  ('Titas', 'Comilla'),
  ('Burichang', 'Comilla'),
  ('Lalmai', 'Comilla'),
  ('Chhagalnaiya', 'Feni'),
  ('Feni Sadar', 'Feni'),
  ('Sonagazi', 'Feni'),
  ('Fulgazi', 'Feni'),
  ('Parshuram', 'Feni'),
  ('Daganbhuiyan', 'Feni'),
  ('Brahmanbaria Sadar', 'Brahmanbaria'),
  ('Kasba', 'Brahmanbaria'),
  ('Nasirnagar', 'Brahmanbaria'),
  ('Sarail', 'Brahmanbaria'),
  ('Ashuganj', 'Brahmanbaria'),
  ('Akhaura', 'Brahmanbaria'),
  ('Nabinagar', 'Brahmanbaria'),
  ('Bancharampur', 'Brahmanbaria'),
  ('Bijoynagar', 'Brahmanbaria'),
  ('Rangamati Sadar', 'Rangamati'),
  ('Kaptai', 'Rangamati'),
  ('Kawkhali', 'Rangamati'),
  ('Baghaichari', 'Rangamati'),
  ('Barkal', 'Rangamati'),
  ('Langadu', 'Rangamati'),
  ('Rajasthali', 'Rangamati'),
  ('Belaichari', 'Rangamati'),
  ('Juraichari', 'Rangamati'),
  ('Naniarchar', 'Rangamati'),
  ('Noakhali Sadar', 'Noakhali'),
  ('Companiganj', 'Noakhali'),
  ('Begumganj', 'Noakhali'),
  ('Hatia', 'Noakhali'),
  ('Subarnachar', 'Noakhali'),
  ('Kabirhat', 'Noakhali'),
  ('Senbug', 'Noakhali'),
  ('Chatkhil', 'Noakhali'),
  ('Sonaimori', 'Noakhali'),
  ('Haimchar', 'Chandpur'),
  ('Kachua', 'Chandpur'),
  ('Shahrasti', 'Chandpur'),
  ('Chandpur Sadar', 'Chandpur'),
  ('Matlab South', 'Chandpur'),
  ('Hajiganj', 'Chandpur'),
  ('Matlab North', 'Chandpur'),
  ('Faridgonj', 'Chandpur'),
  ('Lakshmipur Sadar', 'Lakshmipur'),
  ('Kamalnagar', 'Lakshmipur'),
  ('Raipur', 'Lakshmipur'),
  ('Ramgati', 'Lakshmipur'),
  ('Ramganj', 'Lakshmipur'),
  ('Rangunia', 'Chattogram'),
  ('Sitakunda', 'Chattogram'),
  ('Mirsharai', 'Chattogram'),
  ('Patiya', 'Chattogram'),
  ('Sandwip', 'Chattogram'),
  ('Banshkhali', 'Chattogram'),
  ('Boalkhali', 'Chattogram'),
  ('Anwara', 'Chattogram'),
  ('Chandanaish', 'Chattogram'),
  ('Satkania', 'Chattogram'),
  ('Lohagara', 'Chattogram'),
  ('Hathazari', 'Chattogram'),
  ('Fatikchhari', 'Chattogram'),
  ('Raozan', 'Chattogram'),
  ('Karnafuli', 'Chattogram'),
  ('Coxsbazar Sadar', 'Coxsbazar'),
  ('Chakaria', 'Coxsbazar'),
  ('Kutubdia', 'Coxsbazar'),
  ('Ukhiya', 'Coxsbazar'),
  ('Moheshkhali', 'Coxsbazar'),
  ('Pekua', 'Coxsbazar'),
  ('Ramu', 'Coxsbazar'),
  ('Teknaf', 'Coxsbazar'),
  ('Khagrachhari Sadar', 'Khagrachhari'),
  ('Dighinala', 'Khagrachhari'),
  ('Panchari', 'Khagrachhari'),
  ('Laxmichhari', 'Khagrachhari'),
  ('Mohalchari', 'Khagrachhari'),
  ('Manikchari', 'Khagrachhari'),
  ('Ramgarh', 'Khagrachhari'),
  ('Matiranga', 'Khagrachhari'),
  ('Guimara', 'Khagrachhari'),
  ('Bandarban Sadar', 'Bandarban'),
  ('Alikadam', 'Bandarban'),
  ('Naikhongchhari', 'Bandarban'),
  ('Rowangchhari', 'Bandarban'),
  ('Lama', 'Bandarban'),
  ('Ruma', 'Bandarban'),
  ('Thanchi', 'Bandarban'),
  ('Belkuchi', 'Sirajganj'),
  ('Chauhali', 'Sirajganj'),
  ('Kamarkhand', 'Sirajganj'),
  ('Kazipur', 'Sirajganj'),
  ('Raigonj', 'Sirajganj'),
  ('Shahjadpur', 'Sirajganj'),
  ('Sirajganj Sadar', 'Sirajganj'),
  ('Tarash', 'Sirajganj'),
  ('Ullapara', 'Sirajganj'),
  ('Sujanagar', 'Pabna'),
  ('Ishurdi', 'Pabna'),
  ('Bhangura', 'Pabna'),
  ('Pabna Sadar', 'Pabna'),
  ('Bera', 'Pabna'),
  ('Atghoria', 'Pabna'),
  ('Chatmohar', 'Pabna'),
  ('Santhia', 'Pabna'),
  ('Faridpur', 'Pabna'),
  ('Kahaloo', 'Bogura'),
  ('Bogra Sadar', 'Bogura'),
  ('Shariakandi', 'Bogura'),
  ('Shajahanpur', 'Bogura'),
  ('Dupchanchia', 'Bogura'),
  ('Adamdighi', 'Bogura'),
  ('Nondigram', 'Bogura'),
  ('Sonatala', 'Bogura'),
  ('Dhunot', 'Bogura'),
  ('Gabtali', 'Bogura'),
  ('Sherpur', 'Bogura'),
  ('Shibganj', 'Bogura'),
  ('Paba', 'Rajshahi'),
  ('Durgapur', 'Rajshahi'),
  ('Mohonpur', 'Rajshahi'),
  ('Charghat', 'Rajshahi'),
  ('Puthia', 'Rajshahi'),
  ('Bagha', 'Rajshahi'),
  ('Godagari', 'Rajshahi'),
  ('Tanore', 'Rajshahi'),
  ('Bagmara', 'Rajshahi'),
  ('Natore Sadar', 'Natore'),
  ('Singra', 'Natore'),
  ('Baraigram', 'Natore'),
  ('Bagatipara', 'Natore'),
  ('Lalpur', 'Natore'),
  ('Gurudaspur', 'Natore'),
  ('Naldanga', 'Natore'),
  ('Akkelpur', 'Joypurhat'),
  ('Kalai', 'Joypurhat'),
  ('Khetlal', 'Joypurhat'),
  ('Panchbibi', 'Joypurhat'),
  ('Joypurhat Sadar', 'Joypurhat'),
  ('Chapainawabganj Sadar', 'Chapainawabganj'),
  ('Gomostapur', 'Chapainawabganj'),
  ('Nachol', 'Chapainawabganj'),
  ('Bholahat', 'Chapainawabganj'),
  ('Shibganj', 'Chapainawabganj'),
  ('Mohadevpur', 'Naogaon'),
  ('Badalgachi', 'Naogaon'),
  ('Patnitala', 'Naogaon'),
  ('Dhamoirhat', 'Naogaon'),
  ('Niamatpur', 'Naogaon'),
  ('Manda', 'Naogaon'),
  ('Atrai', 'Naogaon'),
  ('Raninagar', 'Naogaon'),
  ('Naogaon Sadar', 'Naogaon'),
  ('Porsha', 'Naogaon'),
  ('Sapahar', 'Naogaon'),
  ('Manirampur', 'Jashore'),
  ('Abhaynagar', 'Jashore'),
  ('Bagherpara', 'Jashore'),
  ('Chougachha', 'Jashore'),
  ('Jhikargacha', 'Jashore'),
  ('Keshabpur', 'Jashore'),
  ('Jessore Sadar', 'Jashore'),
  ('Sharsha', 'Jashore'),
  ('Assasuni', 'Satkhira'),
  ('Debhata', 'Satkhira'),
  ('Kalaroa', 'Satkhira'),
  ('Satkhira Sadar', 'Satkhira'),
  ('Shyamnagar', 'Satkhira'),
  ('Tala', 'Satkhira'),
  ('Kaliganj', 'Satkhira'),
  ('Mujibnagar', 'Meherpur'),
  ('Meherpur Sadar', 'Meherpur'),
  ('Gangni', 'Meherpur'),
  ('Narail Sadar', 'Narail'),
  ('Lohagara', 'Narail'),
  ('Kalia', 'Narail'),
  ('Chuadanga Sadar', 'Chuadanga'),
  ('Alamdanga', 'Chuadanga'),
  ('Damurhuda', 'Chuadanga'),
  ('Jibannagar', 'Chuadanga'),
  ('Kushtia Sadar', 'Kushtia'),
  ('Kumarkhali', 'Kushtia'),
  ('Khoksa', 'Kushtia'),
  ('Mirpur', 'Kushtia'),
  ('Daulatpur', 'Kushtia'),
  ('Bheramara', 'Kushtia'),
  ('Shalikha', 'Magura'),
  ('Sreepur', 'Magura'),
  ('Magura Sadar', 'Magura'),
  ('Mohammadpur', 'Magura'),
  ('Paikgasa', 'Khulna'),
  ('Fultola', 'Khulna'),
  ('Digholia', 'Khulna'),
  ('Rupsha', 'Khulna'),
  ('Terokhada', 'Khulna'),
  ('Dumuria', 'Khulna'),
  ('Botiaghata', 'Khulna'),
  ('Dakop', 'Khulna'),
  ('Koyra', 'Khulna'),
  ('Fakirhat', 'Bagerhat'),
  ('Bagerhat Sadar', 'Bagerhat'),
  ('Mollahat', 'Bagerhat'),
  ('Sarankhola', 'Bagerhat'),
  ('Rampal', 'Bagerhat'),
  ('Morrelganj', 'Bagerhat'),
  ('Kachua', 'Bagerhat'),
  ('Mongla', 'Bagerhat'),
  ('Chitalmari', 'Bagerhat'),
  ('Jhenaidah Sadar', 'Jhenaidah'),
  ('Shailkupa', 'Jhenaidah'),
  ('Harinakundu', 'Jhenaidah'),
  ('Kaliganj', 'Jhenaidah'),
  ('Kotchandpur', 'Jhenaidah'),
  ('Moheshpur', 'Jhenaidah'),
  ('Jhalakathi Sadar', 'Jhalakathi'),
  ('Kathalia', 'Jhalakathi'),
  ('Nalchity', 'Jhalakathi'),
  ('Rajapur', 'Jhalakathi'),
  ('Bauphal', 'Patuakhali'),
  ('Patuakhali Sadar', 'Patuakhali'),
  ('Dumki', 'Patuakhali'),
  ('Dashmina', 'Patuakhali'),
  ('Kalapara', 'Patuakhali'),
  ('Mirzaganj', 'Patuakhali'),
  ('Galachipa', 'Patuakhali'),
  ('Rangabali', 'Patuakhali'),
  ('Pirojpur Sadar', 'Pirojpur'),
  ('Nazirpur', 'Pirojpur'),
  ('Kawkhali', 'Pirojpur'),
  ('Zianagar', 'Pirojpur'),
  ('Bhandaria', 'Pirojpur'),
  ('Mathbaria', 'Pirojpur'),
  ('Nesarabad', 'Pirojpur'),
  ('Barisal Sadar', 'Barisal'),
  ('Bakerganj', 'Barisal'),
  ('Babuganj', 'Barisal'),
  ('Wazirpur', 'Barisal'),
  ('Banaripara', 'Barisal'),
  ('Gournadi', 'Barisal'),
  ('Agailjhara', 'Barisal'),
  ('Mehendiganj', 'Barisal'),
  ('Muladi', 'Barisal'),
  ('Hizla', 'Barisal'),
  ('Bhola Sadar', 'Bhola'),
  ('Borhan Sddin', 'Bhola'),
  ('Charfesson', 'Bhola'),
  ('Doulatkhan', 'Bhola'),
  ('Monpura', 'Bhola'),
  ('Tazumuddin', 'Bhola'),
  ('Lalmohan', 'Bhola'),
  ('Amtali', 'Barguna'),
  ('Barguna Sadar', 'Barguna'),
  ('Betagi', 'Barguna'),
  ('Bamna', 'Barguna'),
  ('Pathorghata', 'Barguna'),
  ('Taltali', 'Barguna'),
  ('Balaganj', 'Sylhet'),
  ('Beanibazar', 'Sylhet'),
  ('Bishwanath', 'Sylhet'),
  ('Companiganj', 'Sylhet'),
  ('Fenchuganj', 'Sylhet'),
  ('Golapganj', 'Sylhet'),
  ('Gowainghat', 'Sylhet'),
  ('Jaintiapur', 'Sylhet'),
  ('Kanaighat', 'Sylhet'),
  ('Sylhet Sadar', 'Sylhet'),
  ('Zakiganj', 'Sylhet'),
  ('Dakshinsurma', 'Sylhet'),
  ('Osmaninagar', 'Sylhet'),
  ('Barlekha', 'Moulvibazar'),
  ('Kamolganj', 'Moulvibazar'),
  ('Kulaura', 'Moulvibazar'),
  ('Moulvibazar Sadar', 'Moulvibazar'),
  ('Rajnagar', 'Moulvibazar'),
  ('Sreemangal', 'Moulvibazar'),
  ('Juri', 'Moulvibazar'),
  ('Nabiganj', 'Habiganj'),
  ('Bahubal', 'Habiganj'),
  ('Ajmiriganj', 'Habiganj'),
  ('Baniachong', 'Habiganj'),
  ('Lakhai', 'Habiganj'),
  ('Chunarughat', 'Habiganj'),
  ('Habiganj Sadar', 'Habiganj'),
  ('Madhabpur', 'Habiganj'),
  ('Sunamganj Sadar', 'Sunamganj'),
  ('South Sunamganj', 'Sunamganj'),
  ('Bishwambarpur', 'Sunamganj'),
  ('Chhatak', 'Sunamganj'),
  ('Jagannathpur', 'Sunamganj'),
  ('Dowarabazar', 'Sunamganj'),
  ('Tahirpur', 'Sunamganj'),
  ('Dharmapasha', 'Sunamganj'),
  ('Jamalganj', 'Sunamganj'),
  ('Shalla', 'Sunamganj'),
  ('Derai', 'Sunamganj'),
  ('Belabo', 'Narsingdi'),
  ('Monohardi', 'Narsingdi'),
  ('Narsingdi Sadar', 'Narsingdi'),
  ('Palash', 'Narsingdi'),
  ('Raipura', 'Narsingdi'),
  ('Shibpur', 'Narsingdi'),
  ('Kaliganj', 'Gazipur'),
  ('Kaliakair', 'Gazipur'),
  ('Kapasia', 'Gazipur'),
  ('Gazipur Sadar', 'Gazipur'),
  ('Sreepur', 'Gazipur'),
  ('Shariatpur Sadar', 'Shariatpur'),
  ('Naria', 'Shariatpur'),
  ('Zajira', 'Shariatpur'),
  ('Gosairhat', 'Shariatpur'),
  ('Bhedarganj', 'Shariatpur'),
  ('Damudya', 'Shariatpur'),
  ('Araihazar', 'Narayanganj'),
  ('Bandar', 'Narayanganj'),
  ('Narayanganj Sadar', 'Narayanganj'),
  ('Rupganj', 'Narayanganj'),
  ('Sonargaon', 'Narayanganj'),
  ('Basail', 'Tangail'),
  ('Bhuapur', 'Tangail'),
  ('Delduar', 'Tangail'),
  ('Ghatail', 'Tangail'),
  ('Gopalpur', 'Tangail'),
  ('Madhupur', 'Tangail'),
  ('Mirzapur', 'Tangail'),
  ('Nagarpur', 'Tangail'),
  ('Sakhipur', 'Tangail'),
  ('Tangail Sadar', 'Tangail'),
  ('Kalihati', 'Tangail'),
  ('Dhanbari', 'Tangail'),
  ('Itna', 'Kishoreganj'),
  ('Katiadi', 'Kishoreganj'),
  ('Bhairab', 'Kishoreganj'),
  ('Tarail', 'Kishoreganj'),
  ('Hossainpur', 'Kishoreganj'),
  ('Pakundia', 'Kishoreganj'),
  ('Kuliarchar', 'Kishoreganj'),
  ('Kishoreganj Sadar', 'Kishoreganj'),
  ('Karimgonj', 'Kishoreganj'),
  ('Bajitpur', 'Kishoreganj'),
  ('Austagram', 'Kishoreganj'),
  ('Mithamoin', 'Kishoreganj'),
  ('Nikli', 'Kishoreganj'),
  ('Harirampur', 'Manikganj'),
  ('Saturia', 'Manikganj'),
  ('Manikganj Sadar', 'Manikganj'),
  ('Gior', 'Manikganj'),
  ('Shibaloy', 'Manikganj'),
  ('Doulatpur', 'Manikganj'),
  ('Singiar', 'Manikganj'),
  ('Savar', 'Dhaka'),
  ('Dhamrai', 'Dhaka'),
  ('Keraniganj', 'Dhaka'),
  ('Nawabganj', 'Dhaka'),
  ('Dohar', 'Dhaka'),
  ('Munshiganj Sadar', 'Munshiganj'),
  ('Sreenagar', 'Munshiganj'),
  ('Sirajdikhan', 'Munshiganj'),
  ('Louhajanj', 'Munshiganj'),
  ('Gajaria', 'Munshiganj'),
  ('Tongibari', 'Munshiganj'),
  ('Rajbari Sadar', 'Rajbari'),
  ('Goalanda', 'Rajbari'),
  ('Pangsa', 'Rajbari'),
  ('Baliakandi', 'Rajbari'),
  ('Kalukhali', 'Rajbari'),
  ('Madaripur Sadar', 'Madaripur'),
  ('Shibchar', 'Madaripur'),
  ('Kalkini', 'Madaripur'),
  ('Rajoir', 'Madaripur'),
  ('Gopalganj Sadar', 'Gopalganj'),
  ('Kashiani', 'Gopalganj'),
  ('Tungipara', 'Gopalganj'),
  ('Kotalipara', 'Gopalganj'),
  ('Muksudpur', 'Gopalganj'),
  ('Faridpur Sadar', 'Faridpur'),
  ('Alfadanga', 'Faridpur'),
  ('Boalmari', 'Faridpur'),
  ('Sadarpur', 'Faridpur'),
  ('Nagarkanda', 'Faridpur'),
  ('Bhanga', 'Faridpur'),
  ('Charbhadrasan', 'Faridpur'),
  ('Madhukhali', 'Faridpur'),
  ('Saltha', 'Faridpur'),
  ('Panchagarh Sadar', 'Panchagarh'),
  ('Debiganj', 'Panchagarh'),
  ('Boda', 'Panchagarh'),
  ('Atwari', 'Panchagarh'),
  ('Tetulia', 'Panchagarh'),
  ('Nawabganj', 'Dinajpur'),
  ('Birganj', 'Dinajpur'),
  ('Ghoraghat', 'Dinajpur'),
  ('Birampur', 'Dinajpur'),
  ('Parbatipur', 'Dinajpur'),
  ('Bochaganj', 'Dinajpur'),
  ('Kaharol', 'Dinajpur'),
  ('Fulbari', 'Dinajpur'),
  ('Dinajpur Sadar', 'Dinajpur'),
  ('Hakimpur', 'Dinajpur'),
  ('Khansama', 'Dinajpur'),
  ('Birol', 'Dinajpur'),
  ('Chirirbandar', 'Dinajpur'),
  ('Lalmonirhat Sadar', 'Lalmonirhat'),
  ('Kaliganj', 'Lalmonirhat'),
  ('Hatibandha', 'Lalmonirhat'),
  ('Patgram', 'Lalmonirhat'),
  ('Aditmari', 'Lalmonirhat'),
  ('Syedpur', 'Nilphamari'),
  ('Domar', 'Nilphamari'),
  ('Dimla', 'Nilphamari'),
  ('Jaldhaka', 'Nilphamari'),
  ('Kishorganj', 'Nilphamari'),
  ('Nilphamari Sadar', 'Nilphamari'),
  ('Sadullapur', 'Gaibandha'),
  ('Gaibandha Sadar', 'Gaibandha'),
  ('Palashbari', 'Gaibandha'),
  ('Saghata', 'Gaibandha'),
  ('Gobindaganj', 'Gaibandha'),
  ('Sundarganj', 'Gaibandha'),
  ('Phulchari', 'Gaibandha'),
  ('Thakurgaon Sadar', 'Thakurgaon'),
  ('Pirganj', 'Thakurgaon'),
  ('Ranisankail', 'Thakurgaon'),
  ('Haripur', 'Thakurgaon'),
  ('Baliadangi', 'Thakurgaon'),
  ('Rangpur Sadar', 'Rangpur'),
  ('Gangachara', 'Rangpur'),
  ('Taragonj', 'Rangpur'),
  ('Badargonj', 'Rangpur'),
  ('Mithapukur', 'Rangpur'),
  ('Pirgonj', 'Rangpur'),
  ('Kaunia', 'Rangpur'),
  ('Pirgacha', 'Rangpur'),
  ('Kurigram Sadar', 'Kurigram'),
  ('Nageshwari', 'Kurigram'),
  ('Bhurungamari', 'Kurigram'),
  ('Phulbari', 'Kurigram'),
  ('Rajarhat', 'Kurigram'),
  ('Ulipur', 'Kurigram'),
  ('Chilmari', 'Kurigram'),
  ('Rowmari', 'Kurigram'),
  ('Charrajibpur', 'Kurigram'),
  ('Sherpur Sadar', 'Sherpur'),
  ('Nalitabari', 'Sherpur'),
  ('Sreebordi', 'Sherpur'),
  ('Nokla', 'Sherpur'),
  ('Jhenaigati', 'Sherpur'),
  ('Fulbaria', 'Mymensingh'),
  ('Trishal', 'Mymensingh'),
  ('Bhaluka', 'Mymensingh'),
  ('Muktagacha', 'Mymensingh'),
  ('Mymensingh Sadar', 'Mymensingh'),
  ('Dhobaura', 'Mymensingh'),
  ('Phulpur', 'Mymensingh'),
  ('Haluaghat', 'Mymensingh'),
  ('Gouripur', 'Mymensingh'),
  ('Gafargaon', 'Mymensingh'),
  ('Iswarganj', 'Mymensingh'),
  ('Nandail', 'Mymensingh'),
  ('Tarakanda', 'Mymensingh'),
  ('Jamalpur Sadar', 'Jamalpur'),
  ('Melandah', 'Jamalpur'),
  ('Islampur', 'Jamalpur'),
  ('Dewangonj', 'Jamalpur'),
  ('Sarishabari', 'Jamalpur'),
  ('Madarganj', 'Jamalpur'),
  ('Bokshiganj', 'Jamalpur'),
  ('Barhatta', 'Netrokona'),
  ('Durgapur', 'Netrokona'),
  ('Kendua', 'Netrokona'),
  ('Atpara', 'Netrokona'),
  ('Madan', 'Netrokona'),
  ('Khaliajuri', 'Netrokona'),
  ('Kalmakanda', 'Netrokona'),
  ('Mohongonj', 'Netrokona'),
  ('Purbadhala', 'Netrokona'),
  ('Netrokona Sadar', 'Netrokona'),
  ('Eidgaon', 'Coxsbazar'),
  ('Madhyanagar', 'Sunamganj'),
  ('Dasar', 'Madaripur'),
  ('Adabor', 'Dhaka'),
  ('Badda', 'Dhaka'),
  ('Banani', 'Dhaka'),
  ('Bangshal', 'Dhaka'),
  ('Bimanbandar', 'Dhaka'),
  ('Cantonment', 'Dhaka'),
  ('Chalkbazar', 'Dhaka'),
  ('Dakshinkhan', 'Dhaka'),
  ('Darus-Salam', 'Dhaka'),
  ('Demra', 'Dhaka'),
  ('Dhanmondi', 'Dhaka'),
  ('Gandaria', 'Dhaka'),
  ('Gulshan', 'Dhaka'),
  ('Hazaribag', 'Dhaka'),
  ('Jatrabari', 'Dhaka'),
  ('Kafrul', 'Dhaka'),
  ('Kalabagan', 'Dhaka'),
  ('Kamrangirchar', 'Dhaka'),
  ('Khilgaon', 'Dhaka'),
  ('Khilkhet', 'Dhaka'),
  ('Kadamtoli', 'Dhaka'),
  ('Kotwali', 'Dhaka'),
  ('Lalbagh', 'Dhaka'),
  ('Mirpur Model', 'Dhaka'),
  ('Mohammadpur', 'Dhaka'),
  ('Motijheel', 'Dhaka'),
  ('Mugda', 'Dhaka'),
  ('New Market', 'Dhaka'),
  ('Pallabi', 'Dhaka'),
  ('Paltan Model', 'Dhaka'),
  ('Ramna Model', 'Dhaka'),
  ('Rampura', 'Dhaka'),
  ('Rupnagar', 'Dhaka'),
  ('Sabujbag', 'Dhaka'),
  ('Shah Ali', 'Dhaka'),
  ('Shahbagh', 'Dhaka'),
  ('Shahjahanpur', 'Dhaka'),
  ('Sutrapur', 'Dhaka'),
  ('Shyampur', 'Dhaka'),
  ('Sher-e-Bangla Nagar', 'Dhaka'),
  ('Tejgaon Industrial', 'Dhaka'),
  ('Tejgaon', 'Dhaka'),
  ('Turag', 'Dhaka'),
  ('Uttara East', 'Dhaka'),
  ('Uttara West', 'Dhaka'),
  ('Uttarkhan', 'Dhaka'),
  ('Bhashantek', 'Dhaka'),
  ('Vatara', 'Dhaka'),
  ('Wari', 'Dhaka'),
  ('Sadar', 'Gazipur'),
  ('Bason', 'Gazipur'),
  ('Konabari', 'Gazipur'),
  ('Kashimpur', 'Gazipur'),
  ('Gacha', 'Gazipur'),
  ('Pubail', 'Gazipur'),
  ('Tongi East', 'Gazipur'),
  ('Tongi West', 'Gazipur');
